//! Native heap objects for builtin classes: vtable-based mark / flag / drop (C++-style dynamic dispatch).
//! GC holds only `*mut LVoid`; dispatch goes through [NativePropHeader::vtable].
//! Instance `nativePtr` slot helpers and lazy `Box` allocation live here as well.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use boyia_vm::{
    BoyiaFunction, LInt, LIntPtr, LUintPtr, LVoid, Runtime, ValueType,
};

/// GC color bits for native objects (match `gc.rs` `K_BOYIA_GC_*`).
pub const K_NATIVE_GC_WHITE: u8 = 0;
pub const K_NATIVE_GC_BLACK: u8 = 2;

/// Per-type vtable: one static instance per native builtin struct (generated by `#[boyia_native_object]`).
#[repr(C)]
pub struct NativePropVTable {
    pub mark_fn: unsafe fn(*mut LVoid, u8),
    pub flag_fn: unsafe fn(*mut LVoid) -> u8,
    pub drop_fn: unsafe fn(*mut LVoid),
}

/// Prefix of every `Box<T>` native object; must be the first field of `T` (`#[repr(C)]`).
#[repr(C)]
pub struct NativePropHeader {
    pub vtable: *const NativePropVTable,
    pub gc_mark: u8,
    _pad: [u8; 7],
}

impl NativePropHeader {
    #[inline]
    pub fn new(vtable: &'static NativePropVTable) -> Self {
        Self {
            vtable,
            gc_mark: K_NATIVE_GC_WHITE,
            _pad: [0; 7],
        }
    }
}

/// Implemented by each `#[boyia_native_object]` struct (macro-generated).
pub trait NativePropTrait: Sized {
    const VTABLE: NativePropVTable;

    fn boyia_default() -> Self;

    #[inline]
    unsafe fn native_mark(ptr: *mut LVoid, color: u8) {
        (*header(ptr)).gc_mark = color;
    }

    #[inline]
    unsafe fn native_flag(ptr: *mut LVoid) -> u8 {
        (*header(ptr)).gc_mark
    }

    unsafe fn native_drop(ptr: *mut LVoid);
}

#[inline]
pub unsafe fn header(ptr: *mut LVoid) -> *mut NativePropHeader {
    ptr as *mut NativePropHeader
}

#[inline]
pub unsafe fn mark(ptr: *mut LVoid, color: LInt) {
    if ptr.is_null() {
        return;
    }
    let hdr = &mut *header(ptr);
    let Some(vt) = hdr.vtable.as_ref() else {
        hdr.gc_mark = color as u8;
        return;
    };
    (vt.mark_fn)(ptr, color as u8);
}

#[inline]
pub fn flag(ptr: *mut LVoid) -> LInt {
    if ptr.is_null() {
        return K_NATIVE_GC_WHITE as LInt;
    }
    unsafe {
        let hdr = &*header(ptr);
        hdr.vtable
            .as_ref()
            .map(|vt| (vt.flag_fn)(ptr) as LInt)
            .unwrap_or(hdr.gc_mark as LInt)
    }
}

#[inline]
pub unsafe fn drop_native(ptr: *mut LVoid) {
    if ptr.is_null() {
        return;
    }
    let hdr = &*header(ptr);
    if let Some(vt) = hdr.vtable.as_ref() {
        (vt.drop_fn)(ptr);
    }
}

// ---------------------------------------------------------------------------
// Instance `nativePtr` slot (index 0) on Boyia class objects
// ---------------------------------------------------------------------------

pub const BOYIA_NATIVE_PTR_SLOT: usize = 0;
pub const BOYIA_NATIVE_PTR_NAME: &str = "nativePtr";

/// Append slot 0 (`nativePtr`, `BY_NAVCLASS`, 0) on the class template body.
pub unsafe fn attach_native_ptr_slot(
    class_body: *mut BoyiaFunction,
    gen_id: &mut dyn FnMut(&str) -> LUintPtr,
) {
    if class_body.is_null() || (*class_body).mParams.is_null() {
        return;
    }
    let slot = (*class_body).mParams.add((*class_body).mParamSize as usize);
    (*slot).mNameKey = gen_id(BOYIA_NATIVE_PTR_NAME);
    (*slot).mValueType = ValueType::BY_NAVCLASS;
    (*slot).mValue.mIntVal = 0;
    (*class_body).mParamSize += 1;
}

pub unsafe fn set_native_ptr(instance: *mut BoyiaFunction, ptr: *mut LVoid) {
    if instance.is_null() || (*instance).mParams.is_null() {
        return;
    }
    let slot = (*instance).mParams.add(BOYIA_NATIVE_PTR_SLOT);
    (*slot).mValueType = ValueType::BY_NAVCLASS;
    (*slot).mValue.mIntVal = ptr as LIntPtr;
}

pub unsafe fn get_native_ptr(instance: *mut BoyiaFunction) -> *mut LVoid {
    if instance.is_null() || (*instance).mParams.is_null() {
        return std::ptr::null_mut();
    }
    let slot = (*instance).mParams.add(BOYIA_NATIVE_PTR_SLOT);
    (*slot).mValue.mIntVal as *mut LVoid
}

/// Lazy-alloc `Box<T>` on first use; register with GC via `nativePtr` + `gc_append_ref`.
pub unsafe fn boyia_ensure_native<T: NativePropTrait>(
    instance: *mut BoyiaFunction,
    rt: &mut dyn Runtime,
) -> *mut T {
    let existing = get_native_ptr(instance);
    if !existing.is_null() {
        return existing as *mut T;
    }
    let boxed = Box::new(T::boyia_default());
    let raw = Box::into_raw(boxed);
    set_native_ptr(instance, raw as *mut LVoid);
    rt.gc_append_ref(raw as *mut LVoid, ValueType::BY_NAVCLASS);
    raw
}

pub unsafe fn boyia_native_ref<T: NativePropTrait>(
    instance: *mut BoyiaFunction,
    rt: &mut dyn Runtime,
) -> &T {
    &*boyia_ensure_native::<T>(instance, rt)
}

pub unsafe fn boyia_native_mut<T: NativePropTrait>(
    instance: *mut BoyiaFunction,
    rt: &mut dyn Runtime,
) -> &mut T {
    &mut *boyia_ensure_native::<T>(instance, rt)
}
